### ISSUE TITLE
Client Pool Info

### ISSUE THREAD

**Issue by emaildano** [getshifter/wp-cli-shifter#7]
@miya0001 Is a user client pool ID sensitive data?

I got this error and didn't expect it to give me so much info back.

```
Shifter Username: xxxx
Password (will be hidden): 
Error: User pool client xxxx does not exist in user pool us-east-1_OqeySRZoo.
```

**Comment by miya0001** [comment]
@emaildano 

> Is a user client pool ID sensitive data?

Yes.
But I am not sure why the problem occurred, so I will check it. Thanks!

**Comment by miya0001** [comment]
@horike37 

It looks to be successful for login.
Do you know why was the message returned?

**Comment by horike37** [comment]
>Do you know why was the message returned?

hmm.. I'm not sure. How can reproduce it?

**Comment by emaildano** [comment]
@horike37 

Here is the full output before the error. I've check my pw and it is correct. I've also tried using my email address instead of my Shifter account  username.

```
$ danielolson : ~/dev/mastery [develop]
$ wp shifter archive upload
Shifter Username: emaildano
Password (will be hidden): 
Error: User pool client 3t3ctt40691vpqe76c85772a4g does not exist in user pool us-east-1_OqeySRZoo.
```

![screen shot 2017-01-27 at 4 39 02 pm](https://cloud.githubusercontent.com/assets/1872327/22388707/e62447ea-e4af-11e6-8661-02da9eeb65e4.png)

@miya0001

There is a verify feature in the S3-Uploads plugin that I find very helpful during setup. Is something like this possible?

```
$ danielolson : ~/dev/mastery [develop]
$ wp s3-uploads verify
Attempting to upload file s3://mastery_j2made/uploads/685776348.jpg
File uploaded to S3 successfully.
Attempting to delete file. s3://mastery_j2made/uploads/685776348.jpg
File deleted from S3 successfully.
Success: Looks like your configuration is correct.
```

![screen shot 2017-01-27 at 4 46 49 pm](https://cloud.githubusercontent.com/assets/1872327/22388768/4023423c-e4b0-11e6-9dd0-eca45b2b7e1e.png)

**Comment by sawanoboly** [comment]
NP, It can be always seen with view-source of webUI, too.
