### ISSUE TITLE
undefined method Shifter_CLI\Functions::create_archive()

### ISSUE THREAD

**Issue by sawanoboly** [getshifter/wp-cli-shifter#8]
Fail on creating an archive due to below error.

```
Fatal error: Call to undefined method Shifter_CLI\Functions::create_archive() in /root/.wp-cli/packages/vendor/shifter/cli/lib/archive.php on line 162
```

**Comment by miya0001** [comment]
https://github.com/getshifter/wp-cli-shifter/commit/4c3e43786f98059bd9394dc117a708b4cbbb9309

Maybe fixed. But we have an another error.
https://travis-ci.org/getshifter/wp-cli-shifter/jobs/196073165

@horike37 
Please investigate the cause.

**Comment by miya0001** [comment]
```
User pool client 3t3ctt40691vpqe76c85772a4g does not exist in user pool us-east-1_OqeySRZoo.
```
